accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name = 'logout')
]

articles/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.article_list, name = "list"),
    url(r'^create/$',views.article_create, name = "create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_details, name = "detail"),
    
     
    
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from . import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from articles import views as article_views


urlpatterns = [
    url(r'^accounts/', include( "accounts.urls")),
    url(r'^articles/', include("articles.urls")),
    path('admin/', admin.site.urls),
    url(r'^about/$',views.about),
    url(r'^$',article_views.article_list,name="home"),
   
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='me.jpg', blank =True)
    author = models.ForeignKey(User,on_delete=models.CASCADE, default = None)
     
    # add thumbnail later
    # add author later
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:20] + '...'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ["title", "body","slug", "thumb"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user )

            return redirect('articles:list')
            

        #log user in

    else:
        form = UserCreationForm()
        
        

    
    return render(request, 'accounts/signup.html', {'form': form})
    
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
            
        #login the user
        

    else:
        form = AuthenticationForm()
        
    
    return render(request, 'accounts/login.html', {'form': form})
    
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from . import forms
from django.contrib.auth.decorators import login_required

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})
    
def article_details(request, slug) :

    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

    # return HttpResponse(slug )
@login_required(login_url ="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    
    form = forms.CreateArticle()
    return render(request, 'articles/article_create.html',{'form':form} )

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def about(request):
    #return HttpResponse("Hello this is the about page")
    return render(request, 'about.html')

def home(request):
    #return HttpResponse("homepage")
    return render(request, 'homepage.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>Log in</h1>
<form class="site-form" action="/accounts/login/"  method="post">
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
       <input type="hidden" name ="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Log in">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>Sign up</h1>
<form class="site-form" action = "/accounts/signup/" method = "post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="sign up">
</form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="create-article">
    <h2>Create an awesome new article</h2>
    <form action="/articles/create/" class="site-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
    {{form}}
    <input type="submit" value="create">
    </form>
    
</div>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{article.thumb.url }}" alt="">
        <h2>{{article.title}}</h2>
        <p>{{article.body}}</p>
        <p>{{article.author}} -- {{article.date}}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %} {% block content %}

<h1>Olvine's Favorite Poems and Stories</h1>
<div class="articles">
  {% for article in articles %}
  <div class="article">
    <h2>
      <a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a>
    </h2>
     
    <p>{{ article.snippet }}</p>
    <p class="date"> {{ article.date }}</p>
    <p class="author">Added by {{article.author.username}}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/about.html
 {% extends 'base_layout.html' %}
 {% block content %}
    <h1>About us</h1>
    <p>We like django</p>
    {% endblock %}
    

templates/base_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Article</title>
    <link rel="stylesheet" href="/static/styles.css">
</head>
<body>
    <header class = "wrapper">
        <h1><a href="{% url 'home' %}">Home</a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="/accounts/logout/" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                    </form>

                </li>
                <li><a class="highlight" href="{% url 'articles:create' %}">New Article</a></li>
                {% else %} 
                   
                  <li> <a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
        </header>
        <div class="wrapper"> 
        {% block content %}
        {% endblock %}
    </div>
    
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="/static/styles.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the homepage</h1>
    <p>Welcome to DjangoNaustic</p>
    
</body>
</html>